openapi: 3.0.0
info:
  title: UXReality Respondent Android
  version: '2.0'
  contact:
    name: Sergey
  description: Описание когда-то будет
servers:
  - url: 'https://test3.2futureresearch.com'
    description: BASE_URL
paths:
  /GetProjectInfo:
    get:
      summary: GET Project Info
      tags:
        - Survey
      operationId: GET_project_info
      parameters:
        - schema:
            type: string
          in: query
          name: survey
          required: true
          description: Survey code
      description: |-
        Используется для валидации survey code.
        - Если код валидный возврщается результат
        - Если не валидный 404 ошибка
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: Project Info
                type: object
                description: Short poject info
                x-tags:
                  - Survey
                x-examples:
                  application/json:
                    projectName: UXReality Project (Recordings)
                    projectId: 238287341
                    resources: []
                    neurolabTrackers: '23'
                properties:
                  projectId:
                    type: number
                  projectName:
                    type: string
                  resources:
                    type: array
                    items: {}
                  neurolabTrackers:
                    type: string
              examples:
                application/json:
                  value:
                    projectName: UXReality Project (Recordings)
                    projectId: 238287341
                    resources: []
                    neurolabTrackers: '23'
        '404':
          description: Если код не валидный
  /GetQuestMetadata:
    get:
      summary: Get Quest Info
      tags:
        - Survey
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: quest-metadata
                type: object
                x-examples:
                  application/json:
                    settings:
                      surveyCode: 563kc58
                      projectName: Instruction
                      allowMobileDevices: true
                      version: 1585123747
                      showBrand: true
                      hideQuestionNum: 1
                      hideProjectName: 1
                      startQuestTextHidden: 1
                      endQuestTextHidden: 1
                      collectorName: UXREALITY APP
                      collectorId: 239066165
                      theme: default
                      design:
                        layoutTheme: transparent
                        layoutThemeColor: light
                        controlsTheme: elegant
                        regularFont: "'Segoe UI', Frutiger, 'Frutiger Linotype', 'Dejavu Sans', 'Helvetica Neue', Arial, sans-serif"
                        headersFont: "'Segoe UI', Frutiger, 'Frutiger Linotype', 'Dejavu Sans', 'Helvetica Neue', Arial, sans-serif"
                        fontSize: 1
                        lineHeight: 0.6
                        logoAlignment: '0'
                        activeColor: '#fa5b29'
                        bgColor: '#ffffff'
                      generatedCSS: "<!--This styles are generated by designer-->\r\n<style>\r\n\r\n</style>\r\n<!--End of generated styles-->\r\n"
                      translations:
                        - id: 239066162
                          name: English
                          items:
                            next: Next
                            gettingready: Getting ready...
                            end: Thank you for your response
                            ok: Ok
                            ready: Ready
                            confirm: Confirm
                            proceed: Proceed
                            continue: Continue
                            skipinterview: Skip interview
                            nextinterview: New interview
                            instructions: Instructions
                            processing: Processing...
                            initialization: Initialization...
                            loadingvideo: Loading video...
                            loadingimages: Loading images...
                            syncingdata: Syncing data...
                            websiteloading: Website is loading...
                            preparingeyetracking: Preparing eye tracking session...
                            pleasefollowthecircle: Please follow the circle
                            mobileisnotsupported: This survey is not compatible with mobile devices. Please use desktop instead.
                            disqualified: Thank you for your time. Unfortunately we have already reached required number of interviews with people corresponding special criteria of this survey. We will be glad to meet you next time.
                            surveyfinished: This survey is finished. Thank you for your time.
                            surveypaused: This survey has been paused. Thank you for your time. We will be glad to meet you next time.
                            nonunique: You have already answered this survey
                            externalredirect: Redirecting...
                            skipinterviewconfirm: |-
                              We recommend you to continue the survey.
                              Press OK to continue, press Cancel to abort current interview (your answers will not be stored).
                            implicittestfailmessage: Please be more accurate while passing the test and press the correct keys
                            implicitStrongPreferencefor: Strong preference for
                            implicitSlightPreferencefor: Slight preference for
                            implicitResultDescription: 'Your results were categorized as "strong preference", "slight preference" or "no preference" based on the speed of your responses'
                            implicitResultDescriptionTrainFailed: 'We were not able to process the results of your test, as significant portion of your responses were either too fast or too slow.'
                            implicitContinueText: Continue
                            implicitSkipText: |-
                              We recommend you to continue the test.
                              Press OK to continue, press Cancel to skip the test.
                            wet-dontholdtabletonbody: 'Don’t hold your mobile phone on your body. <br> (sit down at the desk)'
                            wet-dontholdlaptopbody: 'Don’t hold your laptop on your body. <br> (sit down at the desk)'
                            wet-takeglassesoff: 'If you wear glasses, please take them off. <br> (contact lenses are fine)'
                            wet-holdphone: 'Don’t rotate your mobile phone. <br> (hold it horizontally or vertically)'
                            wet-wellilluminated: 'Make sure that you are well illuminated. <br> (face towards windows, turn the lights on)'
                            cam-calibrerror-1: No face detected.
                            cam-calibrerror-21: Face is too dark. Reduce background lights.
                            cam-calibrerror-22: Face is too dark. Try to brighten up your face.
                            cam-calibrerror-3: Face is too bright.
                            cam-calibrerror-41: Your left eye is too dark
                            cam-calibrerror-42: Your right eye is too dark
                            cam-calibrerror-5: 'Image is blurry. Please, hold your device still.'
                            cam-calibrerror-51: 'Ensure that camera is focused on your face, not on contrast background behind you.'
                            cam-calibrerror-6: Align your face towards the camera.
                            cam-calibrerror-7: "Place your head in frame's center"
                            cam-calibrerror-81: "You're sitting too far, move closer to the camera."
                            cam-calibrerror-82: "You're sitting too close, move further from the camera."
                            cam-calibrerror-9: Your face is not evenly illuminated
                            cam-calibrerror-10: 'Take off your glasses, please'
                            cam-howto: How to set up camera
                            cam-pleaseenable: "Can't start the video. Please enable the use of webcam in your browser."
                            cam-otherprogramssing: "Can't start the video. Try closing other programs that might be using your webcam."
                            internet-connection-was-lost: 'Internet connection was lost during the session.<br/>Please reload the page'
                            internet-connection-was-lost-app: Internet connection was lost during the session
                            rankingtarget: Drop items here
                            vrequired: Answer is required
                            vorequired: Open text is required
                            vminsize: 'Minimum {0} characters allowed'
                            vmaxsize: 'Maximum {0} characters allowed'
                            vmin: 'Minimum value is {0}'
                            vmax: 'Maximum value is {0}'
                            vaexact: 'Number of required answers: {0}'
                            vamin: 'Please select at least {0} options'
                            vamax: 'Maximum {0} options allowed'
                            vnumber: Invalid decimal number
                            vint: Not a valid integer
                            vnumonly: Numbers only
                            vemail: Email not valid
                            vphone: Phone number not valid
                            valphaonly: Letters only
                            vtotal: 'Total sum should be {0}'
                            vallrequired: All options are required
                          enabled: 1
                          primary: 1
                          default: 1
                      enableNonUniqueRespondents: 1
                      collectorStatus: 1
                    respondent:
                      uid: 239070979
                      clientId: null
                      status: 0
                      projectId: 239066157
                    items:
                      - id: 239066160
                        order: 1
                        questItemType: 1
                        code: s0
                        cssContext: '239066160'
                        name: First section
                        hideName: 1
                        filterConditionsBlock:
                          operator: or
                          conditionBlocks:
                            - operator: and
                      - id: 239066164
                        order: 2
                        sectionId: 239066160
                        questItemType: 0
                        code: q1
                        cssContext: '239066164'
                        name: |-
                          asdfsadf
                          asdfasdf
                          asdf
                        questionType: 18
                        isRequired: 1
                        minRangeSize: 0
                        filterSectionConditionsBlock:
                          operator: or
                          conditionBlocks:
                            - operator: and
                        filterConditionsBlock:
                          operator: or
                          conditionBlocks:
                            - operator: and
                        alternatives: []
                properties:
                  settings:
                    title: settings
                    type: object
                    properties:
                      surveyCode:
                        type: string
                      projectName:
                        type: string
                      allowMobileDevices:
                        type: boolean
                      version:
                        type: number
                      showBrand:
                        type: boolean
                      hideQuestionNum:
                        type: number
                      hideProjectName:
                        type: number
                      startQuestTextHidden:
                        type: number
                      endQuestTextHidden:
                        type: number
                      collectorName:
                        type: string
                      collectorId:
                        type: number
                      theme:
                        type: string
                      design:
                        type: object
                      generatedCSS:
                        type: string
                      translations:
                        type: array
                        items: {}
                      enableNonUniqueRespondents:
                        type: number
                      collectorStatus:
                        type: number
                  respondent:
                    title: respondent
                    type: object
                    properties:
                      uid:
                        type: number
                        description: Id респондента
                      clientId:
                        type: 'null'
                      status:
                        type: number
                      projectId:
                        type: number
                    required:
                      - uid
                      - clientId
                      - status
                      - projectId
                  items:
                    type: array
                    items:
                      title: question
                      type: object
                      properties:
                        id:
                          type: number
                        order:
                          type: number
                        sectionId:
                          type: number
                        questItemType:
                          type: number
                        code:
                          type: string
                        cssContext:
                          type: string
                        name:
                          type: string
                        questionType:
                          type: number
                        isRequired:
                          type: number
                        minRangeSize:
                          type: number
                        filterSectionConditionsBlock:
                          $ref: '#/paths/~1GetQuestMetadata/get/responses/200/content/application~1json/schema/properties/items/items/properties/filterConditionsBlock'
                        filterConditionsBlock:
                          title: question-filter
                          type: object
                          properties:
                            operator:
                              type: string
                              enum:
                                - or
                                - and
                            conditionBlocks:
                              type: array
                              items:
                                type: object
                                properties:
                                  operator:
                                    type: string
                                    enum:
                                      - or
                                      - and
                                required:
                                  - operator
                          required:
                            - operator
                            - conditionBlocks
                        alternatives:
                          type: array
                          items: {}
                        folderGuid:
                          type: string
                        neurolabTrackers:
                          type:
                            - number
                            - array
                          description: Только для нейровопросов
                          items: {}
                        eyeTrackingWebSiteUrl:
                          type: string
                          description: Только для нейровопросов
                        eyeTrackingWebSiteObjective:
                          type: string
                          description: Только для нейровопросов
                        limitTimeout:
                          type: number
                          minimum: 15
                          maximum: 180
                          description: Только для нейровопрос. Значение в милисекудах
                      required:
                        - id
                        - order
                        - questItemType
                        - code
                        - cssContext
                        - name
                  message:
                    type: string
                    enum:
                      - surveyfinished
                      - surveypaused
              examples:
                application/json:
                  value:
                    settings:
                      surveyCode: 563kc58
                      projectName: Instruction
                      allowMobileDevices: true
                      version: 1585123747
                      showBrand: true
                      hideQuestionNum: 1
                      hideProjectName: 1
                      startQuestTextHidden: 1
                      endQuestTextHidden: 1
                      collectorName: UXREALITY APP
                      collectorId: 239066165
                      theme: default
                      design:
                        layoutTheme: transparent
                        layoutThemeColor: light
                        controlsTheme: elegant
                        regularFont: "'Segoe UI', Frutiger, 'Frutiger Linotype', 'Dejavu Sans', 'Helvetica Neue', Arial, sans-serif"
                        headersFont: "'Segoe UI', Frutiger, 'Frutiger Linotype', 'Dejavu Sans', 'Helvetica Neue', Arial, sans-serif"
                        fontSize: 1
                        lineHeight: 0.6
                        logoAlignment: '0'
                        activeColor: '#fa5b29'
                        bgColor: '#ffffff'
                      generatedCSS: "<!--This styles are generated by designer-->\r\n<style>\r\n\r\n</style>\r\n<!--End of generated styles-->\r\n"
                      translations:
                        - id: 239066162
                          name: English
                          items:
                            next: Next
                            gettingready: Getting ready...
                            end: Thank you for your response
                            ok: Ok
                            ready: Ready
                            confirm: Confirm
                            proceed: Proceed
                            continue: Continue
                            skipinterview: Skip interview
                            nextinterview: New interview
                            instructions: Instructions
                            processing: Processing...
                            initialization: Initialization...
                            loadingvideo: Loading video...
                            loadingimages: Loading images...
                            syncingdata: Syncing data...
                            websiteloading: Website is loading...
                            preparingeyetracking: Preparing eye tracking session...
                            pleasefollowthecircle: Please follow the circle
                            mobileisnotsupported: This survey is not compatible with mobile devices. Please use desktop instead.
                            disqualified: Thank you for your time. Unfortunately we have already reached required number of interviews with people corresponding special criteria of this survey. We will be glad to meet you next time.
                            surveyfinished: This survey is finished. Thank you for your time.
                            surveypaused: This survey has been paused. Thank you for your time. We will be glad to meet you next time.
                            nonunique: You have already answered this survey
                            externalredirect: Redirecting...
                            skipinterviewconfirm: |-
                              We recommend you to continue the survey.
                              Press OK to continue, press Cancel to abort current interview (your answers will not be stored).
                            implicittestfailmessage: Please be more accurate while passing the test and press the correct keys
                            implicitStrongPreferencefor: Strong preference for
                            implicitSlightPreferencefor: Slight preference for
                            implicitResultDescription: 'Your results were categorized as "strong preference", "slight preference" or "no preference" based on the speed of your responses'
                            implicitResultDescriptionTrainFailed: 'We were not able to process the results of your test, as significant portion of your responses were either too fast or too slow.'
                            implicitContinueText: Continue
                            implicitSkipText: |-
                              We recommend you to continue the test.
                              Press OK to continue, press Cancel to skip the test.
                            wet-dontholdtabletonbody: 'Don’t hold your mobile phone on your body. <br> (sit down at the desk)'
                            wet-dontholdlaptopbody: 'Don’t hold your laptop on your body. <br> (sit down at the desk)'
                            wet-takeglassesoff: 'If you wear glasses, please take them off. <br> (contact lenses are fine)'
                            wet-holdphone: 'Don’t rotate your mobile phone. <br> (hold it horizontally or vertically)'
                            wet-wellilluminated: 'Make sure that you are well illuminated. <br> (face towards windows, turn the lights on)'
                            cam-calibrerror-1: No face detected.
                            cam-calibrerror-21: Face is too dark. Reduce background lights.
                            cam-calibrerror-22: Face is too dark. Try to brighten up your face.
                            cam-calibrerror-3: Face is too bright.
                            cam-calibrerror-41: Your left eye is too dark
                            cam-calibrerror-42: Your right eye is too dark
                            cam-calibrerror-5: 'Image is blurry. Please, hold your device still.'
                            cam-calibrerror-51: 'Ensure that camera is focused on your face, not on contrast background behind you.'
                            cam-calibrerror-6: Align your face towards the camera.
                            cam-calibrerror-7: "Place your head in frame's center"
                            cam-calibrerror-81: "You're sitting too far, move closer to the camera."
                            cam-calibrerror-82: "You're sitting too close, move further from the camera."
                            cam-calibrerror-9: Your face is not evenly illuminated
                            cam-calibrerror-10: 'Take off your glasses, please'
                            cam-howto: How to set up camera
                            cam-pleaseenable: "Can't start the video. Please enable the use of webcam in your browser."
                            cam-otherprogramssing: "Can't start the video. Try closing other programs that might be using your webcam."
                            internet-connection-was-lost: 'Internet connection was lost during the session.<br/>Please reload the page'
                            internet-connection-was-lost-app: Internet connection was lost during the session
                            rankingtarget: Drop items here
                            vrequired: Answer is required
                            vorequired: Open text is required
                            vminsize: 'Minimum {0} characters allowed'
                            vmaxsize: 'Maximum {0} characters allowed'
                            vmin: 'Minimum value is {0}'
                            vmax: 'Maximum value is {0}'
                            vaexact: 'Number of required answers: {0}'
                            vamin: 'Please select at least {0} options'
                            vamax: 'Maximum {0} options allowed'
                            vnumber: Invalid decimal number
                            vint: Not a valid integer
                            vnumonly: Numbers only
                            vemail: Email not valid
                            vphone: Phone number not valid
                            valphaonly: Letters only
                            vtotal: 'Total sum should be {0}'
                            vallrequired: All options are required
                          enabled: 1
                          primary: 1
                          default: 1
                      enableNonUniqueRespondents: 1
                      collectorStatus: 1
                    respondent:
                      uid: 239070979
                      clientId: null
                      status: 0
                      projectId: 239066157
                    items:
                      - id: 239066160
                        order: 1
                        questItemType: 1
                        code: s0
                        cssContext: '239066160'
                        name: First section
                        hideName: 1
                        filterConditionsBlock:
                          operator: or
                          conditionBlocks:
                            - operator: and
                      - id: 239066164
                        order: 2
                        sectionId: 239066160
                        questItemType: 0
                        code: q1
                        cssContext: '239066164'
                        name: |-
                          asdfsadf
                          asdfasdf
                          asdf
                        questionType: 18
                        isRequired: 1
                        minRangeSize: 0
                        filterSectionConditionsBlock:
                          operator: or
                          conditionBlocks:
                            - operator: and
                        filterConditionsBlock:
                          operator: or
                          conditionBlocks:
                            - operator: and
                        alternatives: []
      operationId: get-GetQuestMetadata
      parameters:
        - schema:
            type: string
          in: query
          name: survey
          required: true
          description: Код анкеты(survey code). Вводит пользователь
        - schema:
            type: number
            default: 1
            enum:
              - 1
          in: query
          name: create_contact
          required: true
          description: Указывает что нужо создать нового респондента в системе
        - schema:
            type: string
            default: json
            enum:
              - json
          in: query
          name: data-format
          required: true
          description: Возвращаемый формат данных
        - schema:
            type: string
          in: query
          name: deviceId
          description: Уникальный идентификатор устройства
  /CheckRespondentsStatus.ashx:
    post:
      summary: Check Respondent
      operationId: checkRespondent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: string
                  checkResult:
                    type: array
                    items:
                      type: object
                      properties:
                        RespondentId:
                          type: number
                          description: Same respondent id as requested in requestBody
                        Result:
                          type: number
                          default: 1
                          enum:
                            - 0
                            - 1
                          description: '0 - нет, 1 - есть'
                      required:
                        - RespondentId
                        - Result
                required:
                  - res
                  - checkResult
              examples:
                application/json:
                  value:
                    res: 1
                    checkResult:
                      - RespondentId: 239036190
                        Result: 1
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                Respondents:
                  type: array
                  description: Array of respondents ids
                  uniqueItems: true
                  items:
                    type: number
              required:
                - Respondents
      description: Проверяет есть ли респондент(ы) в системе.
      tags:
        - Synchronization
  /UxPostRespondentAnswer.cmd:
    post:
      summary: Post Respondent Answers
      operationId: postRespondentAnswer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: number
                  errorCode:
                    type: number
                    enum:
                      - 410
                    description: Error code 410 - already sent data
                  errormessage:
                    type: string
                    description: Error description text
                  '':
                    type: string
                required:
                  - res
              examples:
                application/json:
                  value:
                    res: 1
                Error:
                  value:
                    res: 0
                    errorCode: 410
      description: Send respondent answer on simple quesions
      requestBody:
        content:
          form:
            schema:
              type: object
              properties:
                uid:
                  type: number
                  description: Respondet id
                answers:
                  type: object
                  required:
                    - q
                    - d
                  properties:
                    q:
                      type: number
                      description: Current question id
                    d:
                      type: array
                      items:
                        anyOf:
                          - $ref: '#/components/schemas/Answer_SingleDropdown'
                          - $ref: '#/components/schemas/Answer_SingleChoice'
                          - $ref: '#/components/schemas/Answer_MultipleChoice'
                          - $ref: '#/components/schemas/Answer_Rating'
                          - $ref: '#/components/schemas/Answer_OpenEnded'
                        description: Stringify Object
                    t:
                      type: number
                      description: Current answer timestamp
                status:
                  type: number
                  enum:
                    - 2
                    - 1
                  description: If last question then status = 2
                lastAnsweredQId:
                  type:
                    - number
                    - string
                  description: 'Can be empty string or null. Need provide when have multiple questions, otherwise will be error'
              required:
                - uid
                - answers
                - status
          application/json:
            schema:
              type: object
              properties:
                '':
                  type: string
        description: ''
      tags:
        - Synchronization
    parameters: []
  /GetUploadTokens.ashx:
    post:
      summary: Get upload endpoint
      operationId: getUploadTokens
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: string
                  files:
                    type: array
                    items: {}
              examples:
                application/json:
                  value:
                    res: '1'
                    files:
                      - OriginalFileName: '[VID_20200226_093838.mp4'
                        UploadUrl: 'https://s3.amazonaws.com/cooltool.static/ProjectContact/ProjectContact_239086446/WebEyeTracker/q_239080159/_VID_20200226_093838.mp4?AWSAccessKeyId=AKIAJK2OK5NFLD3C3BPQ&ContentType=video%2Fmp4&Expires=1585508220&Signature=PGRAwv8dEo7hRrL2UtcIBNSTmcU%3D'
                      - OriginalFileName: "\r\n123.mp4"
                        UploadUrl: 'https://s3.amazonaws.com/cooltool.static/ProjectContact/ProjectContact_239086446/WebEyeTracker/q_239080159/_123.mp4?AWSAccessKeyId=AKIAJK2OK5NFLD3C3BPQ&ContentType=video%2Fmp4&Expires=1585508220&Signature=CQejevlU3wC5RMNpNhuLum8P384%3D'
                      - OriginalFileName: "\r\ntest.mp4]"
                        UploadUrl: 'https://s3.amazonaws.com/cooltool.static/ProjectContact/ProjectContact_239086446/WebEyeTracker/q_239080159/_test.mp4%5D?AWSAccessKeyId=AKIAJK2OK5NFLD3C3BPQ&ContentType=application%2Foctet-stream&Expires=1585508220&Signature=mel06tEUiL7Lt1P8DsGtcOyij4Y%3D'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                questionid:
                  type: number
                respondentid:
                  type: number
                dataType:
                  type: string
                  enum:
                    - responseData
                files:
                  oneOf:
                    - type: array
                      items:
                        type: string
                    - type: string
                ignoreMimeType:
                  type: boolean
                  enum:
                    - 'false'
                webcamTracker:
                  type: boolean
                  enum:
                    - 'true'
                screenShotTracker:
                  type: boolean
                  enum:
                    - 'true'
                webEyeTracker:
                  type: boolean
                  enum:
                    - 'true'
              required:
                - questionid
                - respondentid
                - dataType
                - files
                - ignoreMimeType
            examples:
              application/json:
                value:
                  res: '1'
                  files:
                    - OriginalFileName: '[VID_20200226_093838.mp4'
                      UploadUrl: 'https://s3.amazonaws.com/cooltool.static/ProjectContact/ProjectContact_239086446/WebEyeTracker/q_239080159/_VID_20200226_093838.mp4?AWSAccessKeyId=AKIAJK2OK5NFLD3C3BPQ&ContentType=video%2Fmp4&Expires=1585508220&Signature=PGRAwv8dEo7hRrL2UtcIBNSTmcU%3D'
                    - OriginalFileName: "\r\n123.mp4"
                      UploadUrl: 'https://s3.amazonaws.com/cooltool.static/ProjectContact/ProjectContact_239086446/WebEyeTracker/q_239080159/_123.mp4?AWSAccessKeyId=AKIAJK2OK5NFLD3C3BPQ&ContentType=video%2Fmp4&Expires=1585508220&Signature=CQejevlU3wC5RMNpNhuLum8P384%3D'
                    - OriginalFileName: "\r\ntest.mp4]"
                      UploadUrl: 'https://s3.amazonaws.com/cooltool.static/ProjectContact/ProjectContact_239086446/WebEyeTracker/q_239080159/_test.mp4%5D?AWSAccessKeyId=AKIAJK2OK5NFLD3C3BPQ&ContentType=application%2Foctet-stream&Expires=1585508220&Signature=mel06tEUiL7Lt1P8DsGtcOyij4Y%3D'
      tags:
        - Synchronization
  /DataUploaded.ashx:
    post:
      summary: Set data uploaded
      operationId: dataUploaded
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  res:
                    type: number
                    enum:
                      - '0'
                      - '1'
                    description: Если res=1 - все ок. В другом случае ошибка
                  errormessage:
                    type: string
                  fullerrormessage:
                    type: string
                required:
                  - res
              examples:
                application/json:
                  value:
                    res: 1
                Error:
                  value:
                    res: 0
                    errormessage: Data type is not presented or not supported
                    fullerrormessage: "Exception: Data type is not presented or not supported\r\n   at CoolToolSite.DataUploaded.ProcessRequest(HttpContext context)\r\n"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dataType:
                  type: string
                  enum:
                    - responseData
                filePath:
                  type: string
                files:
                  type: string
                questionid:
                  type: number
                respondentid:
                  type: number
                webcamTracker:
                  type: boolean
                  enum:
                    - 'true'
            examples:
              application/json:
                value:
                  dataType: responseData
                  filePath: 'https://s3.amazonaws.com/cooltool.static/ProjectContactAnswer/ProjectContactAnswer_239063126/WebCamCaptures/index.json'
                  files: wet-job-info.json
                  questionid: 238285786
                  respondentid: 239063064
                  webcamTracker: true
      tags:
        - Synchronization
components:
  schemas:
    Answer_SingleDropdown:
      title: Answer_SingleDropdown
      type: object
      properties:
        a:
          type: number
        elapsedMilliseconds:
          type: number
        lang:
          type: number
      required:
        - a
        - elapsedMilliseconds
        - lang
      description: Simple answer dropdown model
    Answer_SingleChoice:
      $ref: '#/components/schemas/Answer_SingleDropdown'
      title: Answer_SingleChoice
      description: Simple answer one choise model
    Answer_MultipleChoice:
      title: Answer_MultipleChoice
      type: array
      items:
        $ref: '#/components/schemas/Answer_SingleChoice'
      description: Collection of single choice answers
    Answer_OpenEnded:
      title: Answer_OpenEnded
      type: object
      properties:
        a:
          type: number
        t:
          type: string
        ellapsedMiliseconds:
          type: number
        lang:
          type: number
    Answer_Rating:
      title: Answer_Rating
      type: object
      properties:
        a:
          type: number
        v:
          type: string
          example: '5'
          enum:
            - '1'
            - '2'
            - '3'
            - '4'
            - '5'
        elapsedMilliseconds:
          type: number
        lang:
          type: number
      required:
        - a
        - v
        - lang
  securitySchemes: {}
